#data-stage
FROM zelejs/api:dummy as data

#builk-stage
FROM arm32v7/adoptopenjdk:11-jdk

COPY --from=data /usr/local/bin/app.jar /usr/local/bin/app.jar

COPY --from=data /var/local/application.yml /var/local/application.yml
COPY --from=data /var/local/logback-spring.xml /var/local/logback-spring.xml

COPY --from=data /usr/local/bin/deploy.sh /usr/local/bin/deploy.sh
COPY --from=data /usr/local/bin/predeploy.sh /usr/local/bin/predeploy.sh
COPY --from=data /usr/local/bin/deploy-lib.sh /usr/local/bin/deploy-lib.sh

COPY --from=data /usr/local/bin/fix_url.sh /usr/local/bin/fix_url.sh
COPY --from=data /usr/local/bin/entrypoint.sh /usr/local/bin/entrypoint.sh

# COPY --from=data /usr/local/lib/jar-dependency.jar /usr/local/lib/jar-dependency.jar
COPY --from=data /usr/local/bin/deploy-classes.sh /usr/local/bin/deploy-classes.sh


WORKDIR /webapps

CMD ["/bin/sh", "-c", "/usr/local/bin/entrypoint.sh"]
