#builk-stage
FROM adoptopenjdk:11-jdk-hotspot

WORKDIR /webapps

ADD target/*.jar /webapps/app.jar

COPY ./tag/api+dev-standalone/conf/application.yml /webapps/config/application-dev.yml
COPY ./tag/api+dev-standalone/conf/logback-spring.xml /webapps/config/logback-spring.xml

COPY ./tag/api+dev-standalone/script/deploy.sh /usr/local/bin/deploy.sh
COPY ./tag/api+dev-standalone/script/predeploy.sh /usr/local/bin/predeploy.sh
COPY ./tag/api+dev-standalone/script/deploy-lib.sh /usr/local/bin/deploy-lib.sh

COPY ./tag/api+dev-standalone/script/fix_url.sh /usr/local/bin/fix_url.sh

RUN chmod +x /usr/local/bin/deploy.sh
RUN chmod +x /usr/local/bin/predeploy.sh
RUN chmod +x /usr/local/bin/deploy-lib.sh
RUN chmod +x /usr/local/bin/fix_url.sh


CMD ["/bin/sh", "-c", "fix_url.sh && deploy-lib.sh && deploy.sh && java $JAVA_OPTS -jar *.jar --sprint.profiles.active=dev --server.port=8080"]
