@endpoint=http://app1.console.smallsaas.cn:8001

### 返回导航列表
GET {{endpoint}}/api/c/navigation/navigations

### 新增
POST {{endpoint}}/api/c/navigation/navigations
Content-Type: application/json

{
    "name": "nav1"
}

### 修改
@id='10'
PUT {{endpoint}}/api/c/navigation/navigations/{{id}}
Content-Type: application/json

{
    "name": "nav1",
    "path": "/list",
    "desc": "baidu.com",
}

### 删除
@id='10'
DELETE  {{endpoint}}/api/c/navigation/navigations/{{id}}
Content-Type: application/json

{}
