@endpoint=http://localhost:8080

### 发送jar文件至lib目录
POST {{endpoint}}/api/jar/dep/jars/upload/lib
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryAFRaG58f2nIb0mPB

------WebKitFormBoundaryAFRaG58f2nIb0mPB
Content-Disposition: form-data; name="file"

title
------WebKitFormBoundaryAFRaG58f2nIb0mPB
Content-Disposition: attachment; name="file"; filename="jar-deploy-api-1.0.0.jar"

< ./target/jar-deploy-api-1.0.0.jar
------WebKitFormBoundaryAFRaG58f2nIb0mPB--

### 查询根目录下的JAR
//all: 是否显示所有文件
GET {{endpoint}}/api/jar/dep/jars
Content-Type: application/json
### 查询指定目录下的JAR
GET {{endpoint}}/api/jar/dep/jars
?all=true
# &dir=lib


### 检查lib的不匹配项
### majar=true 跳过版本号的比较
GET {{endpoint}}/api/jar/dep/mismatch
?baseJar=jar-dependency-api-1.0.0-standalone.jar
&jar=jar-dependency-api-1.0.0.jar
//&major=true
&major=false

### 返回两个JAR的匹配项
GET {{endpoint}}/api/jar/dep/match
?baseJar=jar-dependency-api-1.0.0-standalone.jar
&jar=jar-dependency-api-1.0.0.jar
&major=true

### 查询jar依赖+checksum
// type: default: md5l
//   supported: adler32,crc32,crc32c,md5,sha1,sha256,sha512
//   endsWith "l", means padToLong
GET {{endpoint}}/api/jar/dep/checksum
?jar=jar-dependency-api-1.0.0-standalone.jar
&pattern=jar-dependency
### 查询指定目录lib下的jar依赖
GET {{endpoint}}/api/jar/dep/checksum
?jar=jar-dependency-api-1.0.0.jar
&dir=lib
&type=md5l

### 依据checksum检查两个jar的更新依赖
GET {{endpoint}}/api/jar/dep/checksum/mismatch
?baseJar=jar-dependency-api-1.0.0-standalone.jar
&jar=jar-dependency-api-1.0.0.jar


### 查询指定目录lib下的jar依赖
GET {{endpoint}}/api/jar/dep
?jar=jar-dependency-api-1.0.0.jar
&dir=lib
&pattern=

### 从JAR解压文件
POST {{endpoint}}/api/jar/dep/extract
Content-Type: application/json

{
    "jar": "jar-dependency-api-1.0.0-standalone.jar",
    "pattern": "lombok",
    "target": "lib"
}

### 查询指定目录lib下的jar的所有文件
GET {{endpoint}}/api/jar/dep/inspect
?jar=jar-dependency-api-1.0.0.jar
# &dir=lib
&pattern=JarDeployEndpoint

### extra file from archiva
POST {{endpoint}}/api/jar/dep/extract
Content-Type: application/json

{
    "dir": "lib",
    "jar": "lombok-1.18.8.jar",
    "pattern": "PatchFixesHider$ExtensionMethod.class",
    "target": "classes"
}


### decompile the javaclass
GET {{endpoint}}/api/jar/dep/decompile
?javaclass=classes/PatchFixesHider$ExtensionMethod.class
&dir=lib

### decompile from dir
GET {{endpoint}}/api/jar/dep/decompile
?dir=lib/classes
&pattern=PatchFixesHider

### decompile java class from jar directly
// dir: path to locate the jar
// pattern: contains string to match the file in jar
// target: the target path to save the ext
// empty:  remove the file after decompile when jar is provided
GET {{endpoint}}/api/jar/dep/decompile
?dir=lib
&jar=lombok-1.18.8.jar
&empty=true
&pattern=Builder
&target=classes


### deploy
// dir: where to locate the class
// pattern:  pattern class files to deploy
// target: where to locate the jar to deploy into
POST {{endpoint}}/api/jar/dep/deploy
Content-Type: application/json

{
    "dir": "classes",
    "pattern": "PatchFixesHider$ExtensionMethod.class",
    "target": "lib",
    "jar": "lombok-1.18.8.jar"
}


### create indexes
GET {{endpoint}}/api/jar/dep/indexes
?jar=jar-dependency-api-1.0.0.jar
# &dir=lib
# &pattern=
&recreate=true
&target=indexes
### depends
GET {{endpoint}}/api/jar/dep/jars
?all=true
# &dir=lib


### deploy class file
POST {{endpoint}}/api/jar/dep/deploy
Content-Type: application/json

{
    "dir": "classes",
    "pattern": "JarDeployEndpoint",
    "jar": "jar-dependency-api-1.0.0.jar"
}
### depends
GET {{endpoint}}/api/jar/dep/checksum
?jar=jar-dependency-api-1.0.0.zip.temp
# &pattern=JarDeployEndpoint
&pattern=.class
# &type=crc32
### depends checksum mismatch
GET {{endpoint}}/api/jar/dep/checksum/mismatch
?baseJar=jar-dependency-api-1.0.0.zip.temp
&jar=jar-dependency-api-1.0.0.jar
### depends 上传jar文件至lib目录
POST {{endpoint}}/api/jar/dep/jars/upload/lib
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryAFRaG58f2nIb0mPB

------WebKitFormBoundaryAFRaG58f2nIb0mPB
Content-Disposition: form-data; name="file"

title
------WebKitFormBoundaryAFRaG58f2nIb0mPB
Content-Disposition: attachment; name="file"; filename="jar-deploy-api-1.0.0.jar"

< ./target/jar-deploy-api-1.0.0.jar
------WebKitFormBoundaryAFRaG58f2nIb0mPB--
### inspect jar
GET {{endpoint}}/api/jar/dep/inspect
?jar=jar-dependency-api-1.0.0.jar
# &dir=lib
&pattern=JarDeployEndpoint
### depends list classes
GET {{endpoint}}/api/jar/dep/jars
?all=true
&dir=classes
### extra classes
POST {{endpoint}}/api/jar/dep/extract
Content-Type: application/json

{
    "jar": "jar-dependency-api-1.0.0.jar",
    "pattern": "JarDeployEndpoint",
    "target": "classes"
}
### depends list lib
GET {{endpoint}}/api/jar/dep/jars
?all=true
&dir=lib
### depends list app
GET {{endpoint}}/api/jar/dep/jars
?all=true



## deploy

### 自动查找standalone部署
POST {{endpoint}}/api/jar/dep/from/amFyLWRlcGxveS1hcGktMS4wLjAuamFy
Content-Type: application/json

### 对比两个jar注入
//POST {{endpoint}}/api/jar/dep/checksum/to/{prodJar}/from/{uatJar}
POST {{endpoint}}/api/jar/dep/checksum/to/{prodJar}/from/{uatJar}
Content-Type: application/json

### 注入
### baseJar 不支持[.jar],需转换为BASE64
//POST {{endpoint}}/api/jar/deploy/to/{baseJar}/from/{jar}
// jar-deploy-api-1.0.0-standalone.jar
//  BASE64 Encode: amFyLWRlcGxveS1hcGktMS4wLjAtc3RhbmRhbG9uZS5qYXI=
// lib/jar-deploy-api-1.0.0.jar
//  BASE64 Encode: bGliL2phci1kZXBsb3ktYXBpLTEuMC4wLmphcg==
//
POST {{endpoint}}/api/jar/deploy/to/amFyLWRlcGxveS1hcGktMS4wLjAtc3RhbmRhbG9uZS5qYXI=/from/bGliL2phci1kZXBsb3ktYXBpLTEuMC4wLmphcg==
Content-Type: application/json


