@endpoint=http://localhost:8086

key="514528" ttl =600000
sign提供smallsee/dev-cli获取signature gen key ttl
####所有接口都需要带&sign参数

### 显示所有表
GET {{endpoint}}/dev/connection


### 执行SQL语句，仅支持 SELECT/select show/SHOW   //SELECT * FROM nft_land不带引号
GET {{endpoint}}/dev/connection?sql=SELECT * FROM nft_player&format=md
可选参数 ?format=md
####所有接口都需要带&sign参数

### 获取数据库数据 pattern=<table_name>
GET {{endpoint}}/dev/connection?pattern=
####所有接口都需要带&sign参数

### 页面输出数据
GET {{endpoint}}/dev/connection/print
####所有接口都需要带&sign参数

### 页面输出数据仅结构
GET {{endpoint}}/dev/connection/print?filter=schema
####所有接口都需要带&sign参数

###下载所有的数据库
GET {{endpoint}}/dev/connection/sql
####所有接口都需要带&sign参数

###下载所有的数据库结构
GET {{endpoint}}/dev/connection/sql?filter=schema
####所有接口都需要带&sign参数

###删除规则
DELETE {{endpoint}}/dev/connection/snapshot/rulers/ming


###新建更新规则/dev/connection/snapshot/rulers/{ruler_file_name}
POST {{endpoint}}/dev/connection/snapshot/rulers/ming

{
    "t_end_user": [1],
    "t_schedule_record": [1,2],
    "nft_player": ["1-10","20-30"],
    "t_config_field": ["*"]
}

###查看具体的命名规则的配置详情
GET {{endpoint}}/dev/connection/snapshot/rulers/akali


###表出所有命名规则文件名称
GET {{endpoint}}/dev/connection/snapshot/rulers

###数据库非全量下载
GET {{endpoint}}/dev/connection/snapshot?ruler=basic&rule=defined&sign=63fa65e3b2dac9bc86dcf184b6be4635



###
GET {{endpoint}}/dev/connection/sqls?query=view