@endpoint=http://localhost:8080

key="514528" ttl =600000
sign提供smallsee/dev-cli获取signature gen key ttl
####所有接口都需要带&sign参数

### 显示所有表
GET {{endpoint}}/dev/connection


### 执行SQL语句，仅支持 SELECT/select show/SHOW   //SELECT * FROM nft_land不带引号
GET {{endpoint}}/dev/connection?sql=SELECT * FROM nft_player&format=md
可选参数 ?format=md
####所有接口都需要带&sign参数

### 获取数据库数据 pattern=<table_name>
GET {{endpoint}}/dev/connection?pattern=
####所有接口都需要带&sign参数

### 页面输出数据
GET {{endpoint}}/dev/connection/print
####所有接口都需要带&sign参数

### 页面输出数据仅结构
GET {{endpoint}}/dev/connection/print?filter=schema
####所有接口都需要带&sign参数

###下载所有的数据库
GET {{endpoint}}/dev/connection/sql
####所有接口都需要带&sign参数

###下载所有的数据库结构
GET {{endpoint}}/dev/connection/sql?filter=schema
####所有接口都需要带&sign参数



