@endpoint=http://localhost:8080


### 显示所有表
GET {{endpoint}}/dev/connection/tables


### 执行SQL语句，仅支持 SELECT/select   //SELECT * FROM nft_land不带引号
GET {{endpoint}}/dev/connection?sql=SELECT * FROM nft_player


### 仅用于获取SCHEMA
GET {{endpoint}}/dev/connection/schema?pattern


### 获取数据库数据 pattern=<table_name>
GET {{endpoint}}/dev/connection?pattern=


### 获取所有数据库数据
GET {{endpoint}}/dev/connection

###下载所有的数据库
GET {{endpoint}}/dev/connection/sql



