@endpoint=http://localhost:8084


### 显示文件列表
GET {{endpoint}}/dev/logs/printFileList


### 显示日志上下文,pattern=<fileName>，filter=<>，time=<date>，均为String
GET {{endpoint}}/dev/logs?pattern=access.log&filter=WARN&time=2022-03-21&logNumber=10


### 显示INFO日志
GET {{endpoint}}/dev/logs/info?pattern=access.log

### 显示WARN日志
GET {{endpoint}}/dev/logs/warn?pattern=access.log


### 显示EORRO日志
GET {{endpoint}}/dev/logs/error?pattern=access.log




